/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "BACKUP_STORAGE_DATA": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_CONN_STRINGS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "createBackupQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "snapperDbBackupBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
